using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace PharmacyManagement
{
    public partial class Ad_StaffInformation : Form
    {
        private DataAccess Da { set; get; }
        public Ad_StaffInformation()
        {
            InitializeComponent();
            this.Da = new DataAccess();
            ShowStaffData();
            AutoGeneratedStaffId();
            btnUpdate.Visible = false;
        }

        private void AutoGeneratedStaffId()
        {
            try
            {
                string query = "select StaffId from StaffInformation order by StaffId desc;";
                var dt = this.Da.ExecuteQueryTable(query);
                string oldId = dt.Rows[0][0].ToString();
                string[] s = oldId.Split('-');
                int temp = Convert.ToInt32(s[1]);
                string newId = "Staff-" + (++temp).ToString();
                this.txtStaffId.Text = newId;
            }
            catch (Exception ex)
            {
                MessageBox.Show("Auto GenerateID Error : " + ex );
            }
            

        }

        private void ShowStaffData()
        {
            try
            {
                string query = "select * from StaffInformation;";
                var ds = this.Da.ExecuteQuery(query);
                this.dgvStaffInfo.DataSource = ds.Tables[0];
            }
            catch (Exception exc)
            {
                MessageBox.Show("Error : " + exc);
            }
        }

        private void ClearInputFild()
        {
            this.txtStaffId.Clear();
            this.txtStaffName.Clear();
            this.cmbWorkType.Text = string.Empty;
            this.nudStaffAge.Value = 0;
            this.txtSalary.Clear();
            this.txtAddress.Clear();
            this.dtpAppointDate.Value = DateTime.Now;
            this.txtContractNo.Clear();
            this.txtSearchStaffId.Clear();
            this.txtfindStaffName.Clear();
        }

        private void btnClear_Click(object sender, EventArgs e)
        {
            ClearInputFild();
            ShowStaffData();
            AutoGeneratedStaffId();
            btnUpdate.Visible = false;
        }

        private void btnInsert_Click(object sender, EventArgs e)
        {
            try
            {
                if(this.txtStaffId.Text=="" || this.txtStaffName.Text=="" || this.cmbWorkType.Text=="" || this.nudStaffAge.Value==0 || this.txtSalary.Text=="" || this.txtAddress.Text=="" || this.dtpAppointDate.Text=="" || this.txtContractNo.Text == "")
                {
                    MessageBox.Show("No found Data !");
                }
                else
                {
                    string query = $"insert into StaffInformation (StaffId,StaffName,WorkType,StaffAge,Salary,Address,AppointDate,ContractNo) values ('{this.txtStaffId.Text}','{this.txtStaffName.Text}','{this.cmbWorkType.Text}','{this.nudStaffAge.Value}','{this.txtSalary.Text}','{this.txtAddress.Text}','{this.dtpAppointDate.Text}','{this.txtContractNo.Text}');";
                    var i = this.Da.ExecuteDMLQuery(query);
                    if (i != 0)
                    {
                        MessageBox.Show("New Staff Data added successfully!");
                        ClearInputFild();
                        ShowStaffData();
                        AutoGeneratedStaffId();

                    }
                    else MessageBox.Show("New Staff Data wasn't added successfully!");
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error : " + ex);
            }
        }

        private void btnRefresh_Click(object sender, EventArgs e)
        {
            ShowStaffData();
        }

        private void btnDeleteData_Click(object sender, EventArgs e)
        {
            try
            {
                int index = this.dgvStaffInfo.CurrentCell.RowIndex;
                DataGridViewRow row = this.dgvStaffInfo.Rows[index];
                string selectedStaffID = row.Cells["StaffID"].Value.ToString();
                string SelectedStaffName = row.Cells["StaffName"].Value.ToString();
               
                var query = $"delete from StaffInformation where StaffId = '{selectedStaffID}' and StaffName = '{SelectedStaffName}';";
                var i = this.Da.ExecuteDMLQuery(query);
                if (i != 0)
                {
                    MessageBox.Show(SelectedStaffName + " Data Deleted successfully!");
                    ShowStaffData();
                }
                else
                {
                    MessageBox.Show("Data  wasn't deleted successfully!");
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Can't Delete " + ex);
            }
        }

        private void btnSearch_Click(object sender, EventArgs e)
        {
            try
            {
                string searchText = this.txtSearchStaffId.Text;
                string query = string.Format("select * from StaffInformation where (StaffId like '%{0}%');", searchText);
                var ds = this.Da.ExecuteQuery(query);
                this.dgvStaffInfo.DataSource = ds.Tables[0];
            }
            catch(Exception ex)
            {
                MessageBox.Show("Error : " + ex);
            }
           
        }

        private void txtfindStaffName_TextChanged(object sender, EventArgs e)
        {
            try
            {
                string searchText = this.txtfindStaffName.Text;
                string query = string.Format("select * from StaffInformation where (StaffName like '%{0}%');", searchText);
                var ds = this.Da.ExecuteQuery(query);
                this.dgvStaffInfo.DataSource = ds.Tables[0];
            }catch(Exception ex)
            {
                MessageBox.Show("Error : " + ex);
            }
          
        }

        private void btnModify_Click(object sender, EventArgs e)
        {
            btnUpdate.Visible = true;
            try
            {
                int index = dgvStaffInfo.CurrentCell.RowIndex;
                if (index >= 0)
                {
                    DataGridViewRow row = dgvStaffInfo.Rows[index];

                    this.txtContractNo.Text = row.Cells["ContractNo"].Value.ToString();
                    this.txtStaffId.Text = row.Cells["StaffId"].Value.ToString();
                    this.txtStaffName.Text = row.Cells["StaffName"].Value.ToString();
                    this.cmbWorkType.Text = row.Cells["WorkType"].Value.ToString();
                    this.nudStaffAge.Text = row.Cells["StaffAge"].Value.ToString();
                    this.txtSalary.Text = row.Cells["Salary"].Value.ToString();
                    this.txtAddress.Text = row.Cells["Address"].Value.ToString();
                    this.dtpAppointDate.Text = row.Cells["AppointDate"].Value.ToString();
                   
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
        }

        private void btnUpdate_Click(object sender, EventArgs e)
        {
            btnUpdate.Visible = false;
            try
            {
                var sql = @"update StaffInformation
                                set StaffName = '" + this.txtStaffName.Text + @"',
                                WorkType = '" + this.cmbWorkType.Text + @"',
                                StaffAge = '" + this.nudStaffAge.Text + @"',
                                Salary = '" + this.txtSalary.Text + @"',
                                Address = '" + this.txtAddress.Text + @"',
                                AppointDate = '" + this.dtpAppointDate.Text + @"',
                                ContractNo = '" + this.txtContractNo.Text + @"'
                                where StaffId = '" + this.txtStaffId.Text + "'; ";
                int count = this.Da.ExecuteDMLQuery(sql);
                MessageBox.Show("Data Update SuccessFully");
                ClearInputFild();
                ShowStaffData();
            }
            catch(Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }
        }
    }
}
